grobidHome: "../grobid-home/"

# path relative to the corpus and template path
dataPath: "resources/dataset/"

models:
  # we configure here how each sequence labeling model should be implemented
  # for feature-engineered CRF, use "wapiti" and possible training parameters are window, epsilon and nbMaxIterations
  # for Deep Learning, use "delft" and select the target DL architecture (see DeLFT library), the training
  # parameters then depends on this selected DL architecture

  - name: "datacat-segmenter"
    # at this time, must always be CRF wapiti, the input sequence size is too large for a Deep Learning implementation
    engine: "wapiti"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.0000001
      window: 50
      nbMaxIterations: 1000
      nbThreads: 16